In [2]:
import numpy as np
#example arrays
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]]) #(3*3 array)
arr2 = np.array([[10,20,30]]) #(1D array)

In [5]:
# Adding 1D array to a 2D (broadcasting)
result = arr1 + arr2


In [6]:
#print the result
print("Array 1:")
print(arr1)
print("\nArray 2:")
print(arr2)
print("nResult of Broadcasting ")
print(result)

Array 1:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Array 2:
[[10 20 30]]
nResult of Broadcasting 
[[11 22 33]
 [14 25 36]
 [17 28 39]]


In [8]:
print(arr2)
print(arr2*2) #scalar multiplication.

[[10 20 30]]
[[20 40 60]]


In [9]:
print(arr1)
print(arr1*2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [ ]:
# try plying with addition multiplication between array
