In [5]:
import numpy as np

In [7]:
c = np.arange(1,10)
c

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
c[0]

1

In [9]:
c[::]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
#:: meaning of all attribute

In [11]:
c[1:5]

array([2, 3, 4, 5])

In [12]:
c[1:7]

array([2, 3, 4, 5, 6, 7])

In [13]:
c[0:9:2]

array([1, 3, 5, 7, 9])

In [14]:
c[:9:2]

array([1, 3, 5, 7, 9])

In [15]:
c[1:9:2]

array([2, 4, 6, 8])

In [18]:
arr1 = np.array([[1,2,3,11],[4,5,6,44],[7,8,9,77]]) #3*4 array
arr2 = np.array([[10,20,30,11,66,77,91,92,188]])
arr1

array([[ 1,  2,  3, 11],
       [ 4,  5,  6, 44],
       [ 7,  8,  9, 77]])

In [19]:
print(arr1)

[[ 1  2  3 11]
 [ 4  5  6 44]
 [ 7  8  9 77]]


In [21]:
arr1[0]

array([ 1,  2,  3, 11])

In [22]:
arr1[0][1]

2

In [23]:
arr1[0][0]

1

In [24]:
arr1[::]

array([[ 1,  2,  3, 11],
       [ 4,  5,  6, 44],
       [ 7,  8,  9, 77]])

In [26]:
arr1[0:1]

array([[ 1,  2,  3, 11]])

In [28]:
arr1[0:2]

array([[ 1,  2,  3, 11],
       [ 4,  5,  6, 44]])

In [30]:
arr1 = np.arange(1,3,0.1)
arr1

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

In [34]:
arr1 = np.linspace(0,3,5)
arr1

array([0.  , 0.75, 1.5 , 2.25, 3.  ])

In [35]:
arr1 = np.linspace(0,3,3)
arr1

array([0. , 1.5, 3. ])

In [36]:
arr1 = np.linspace(0,3,15)
arr1

array([0.        , 0.21428571, 0.42857143, 0.64285714, 0.85714286,
       1.07142857, 1.28571429, 1.5       , 1.71428571, 1.92857143,
       2.14285714, 2.35714286, 2.57142857, 2.78571429, 3.        ])

In [37]:
arr1 = np.linspace(70,90,10) #(70 dekhi start ma 90 samm ma 10 wota number linear spacing wala ma baranara gap chayo)
arr1

array([70.        , 72.22222222, 74.44444444, 76.66666667, 78.88888889,
       81.11111111, 83.33333333, 85.55555556, 87.77777778, 90.        ])