In [2]:
import numpy as np

In [3]:
arr1 = np.array([10,20,30])

In [35]:
arr1

array([10, 20, 30])

In [36]:
arr1.shape

(3,)

In [6]:
arr2 = np.array([[1,2,3],[4,5,6]])

In [7]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
arr2.shape

(2, 3)

In [9]:
arr2.size

6

In [10]:
arr3 = np.array([[1,2,3,4],[5,6,7,8]]) #(2*4)

In [11]:
arr3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
arr3.shape

(2, 4)

In [13]:
arr3.size

8

In [14]:
arr3.ndim #(arr(Tap))

2

In [15]:
arr2.ndim

2

In [37]:
arr1.ndim

1

In [17]:
arr4 = np.array([[[1,2],[3,4]]])

In [18]:
print(arr4)

[[[1 2]
  [3 4]]]


In [19]:
arr4.ndim

3

In [20]:
arr4.shape

(1, 2, 2)

In [21]:
arr4.nbytes

16

In [22]:


arr4.dtype

dtype('int32')

In [23]:
 new_array = np.array([[1.1,2.2],[3.3,4.4]])

In [24]:
new_array

array([[1.1, 2.2],
       [3.3, 4.4]])

In [25]:
new_array.shape

(2, 2)

In [26]:
new_array.size

4

In [27]:
new_array.dtype

dtype('float64')

In [28]:
new_array.nbytes

32

In [29]:
 new_array = np.array([[1.1,2.2],[3.3,4.4]],dtype='float32')

In [30]:
new_array

array([[1.1, 2.2],
       [3.3, 4.4]], dtype=float32)

In [31]:
new_array.nbytes

16

In [32]:
new_array[0]

array([1.1, 2.2], dtype=float32)

In [33]:
next_array = np.array([[1,2,3,4],[6,7,8,9]])
next_array

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [ ]:
next_array.shape

In [ ]:
next_array.size

In [ ]:
next_array.dtype